### ISSUE TITLE
Shopping Speed Upgrade Error

### ISSUE THREAD

**Issue by Johneysteel** [8BitToaster/Monster-Clash#1]
I recieved the following error message while trying to purchase a speed upgrade:

> pygame 1.9.4
> Hello from the pygame community. https://www.pygame.org/contribute.html
> Traceback (most recent call last):
>   File "C:\Users\John\Downloads\Monster-Clash-master\Monster-Clash-master\Monster Clash Alpha 1.00\Game.py", line 1053, in <module>
>     game_loop()
>   File "C:\Users\John\Downloads\Monster-Clash-master\Monster-Clash-master\Monster Clash Alpha 1.00\Game.py", line 554, in game_loop
>     if gold >= SpeedItems[1][2]:
> TypeError: '>=' not supported between instances of 'int' and 'str'

![monster clash error](https://user-images.githubusercontent.com/26022793/50050560-a26ea780-00cc-11e9-8ff0-32bd8fe49619.png)

**Comment by SophieWalden** [comment]
Very sorry this happened to you. If you redownload the game in about an hour it should be fixed.

**Comment by SophieWalden** [comment]
Didn't think anyone would actually play this game. Thanks for the support!
